apiVersion: v1
kind: Service
metadata:
  name: guestbook-frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: guestbook-frontend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80